### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by myst10py** [SamurAIGPT/privateGPT#1]
I'm getting the following runtime error when running locally and after installing all the npm packages with npm i, as well as creating a venv for the python packages and installing all the requirements with pip.

"Unhandled Runtime Error
TypeError: event.target.file is undefined"

<img width="961" alt="Screenshot 2023-05-25 at 10 23 53 AM" src="https://github.com/SamurAIGPT/privateGPT/assets/9206432/1babaece-1b21-4e34-8733-09c87a6029a9">

**Comment by Anil-matcha** [comment]
Updated Readme now with the steps, check it out
