### ISSUE TITLE
Loading models

### ISSUE THREAD

**Issue by ManuXD32** [SamurAIGPT/privateGPT#10]
I have noticed that the app loads the model twice, using more RAM than need it. Is there a reason for that or is it just a bug?

**Comment by ManuXD32** [comment]
> I have noticed that the app loads the model twice, using more RAM than need it. Is there a reason for that or is it just a bug?

Okay, solved, looks like it is because the debug option is set to True by default, changing It to False in the privateGPT.py file solves the problem.

**Comment by Anil-matcha** [comment]
Changed the default load now. Thanks
