### ISSUE TITLE
Doesn't run on non-windows 

### ISSUE THREAD

**Issue by 3chospirits** [SamurAIGPT/privateGPT#12]
Would specify in the requirements that this only works on windows. pywin doesn't work on other OS.

**Comment by Anil-matcha** [comment]
Can you try removing that requirement and run. It should work

**Comment by dsuriano** [comment]
Confirmed @Anil-matcha's suggestion does indeed fix the error I was recieving as well:
`ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)`
`ERROR: No matching distribution found for pywin32==306`

Open `./server/requirements.txt` and remove line `97`: `pywin32==306`.

**Comment by Anil-matcha** [comment]
@3chospirits Closing the issue as has been fixed by https://github.com/SamurAIGPT/privateGPT/pull/17
