### ISSUE TITLE
Server error 404

### ISSUE THREAD

**Issue by dKonsalik** [SamurAIGPT/privateGPT#25]
Hello, I am also getting 404 not found when when going to http://192.168.20.50:5000/

Serving Flask app 'privateGPT'
Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
Running on all addresses (0.0.0.0)
Running on http://127.0.0.1:5000/
Running on http://192.168.20.50:5000/
Press CTRL+C to quit
192.168.70.36 - - [29/May/2023 15:48:07] "GET / HTTP/1.1" 404 -
http://192.168.20.50:3000/ works but can't upload a document gives error

**Comment by joemccann** [comment]
The flask app running on port 5000 is just the backend. You need to run the npm commands in the server directory to start the front end which runs on port 3000.

**Comment by dKonsalik** [comment]
So I have the back end and front end running, but I cannot upload any document, download Model or any other functions
Error uploading document
Error fetching Answer, Please try again
![image](https://github.com/SamurAIGPT/privateGPT/assets/126891646/f012f003-906c-46eb-9214-23d196c7e6d2)

**Comment by Anil-matcha** [comment]
Can  you share the document you are trying to upload ?

**Comment by dKonsalik** [comment]
I can share with you the document, but none of them work, neither the chat, neither download the model
Is there anyway I can check the logs? because I don't know why, nothings works on the application as a said.
[PING_Data.xlsx](https://github.com/SamurAIGPT/privateGPT/files/11593855/PING_Data.xlsx)

**Comment by bradsec** [comment]
Had same issue but I was trying to run PrivateGPT on another PC on the network and access through browser on a different PC. There's a lot of reference to "localhost" in the client folder code, so it you are trying to run on another PC/server, container or vm this isn''t going to work. I had to update the localhost to machine IP to get this to work. This may be something that can be addressed in future not hard coding "localhost".

**Comment by dKonsalik** [comment]
> Had same issue but I was trying to run PrivateGPT on another PC on the network and access through browser on a different PC. There's a lot of reference to "localhost" in the client folder code, so it you are trying to run on another PC/server, container or vm this isn''t going to work. I had to update the localhost references in code to privateGPT host machine IP to get this to work. This may be something that can be addressed in future not hard coding "localhost".

Will you be able to share or let me know which refence files you have changed?

**Comment by dKonsalik** [comment]
> > Had same issue but I was trying to run PrivateGPT on another PC on the network and access through browser on a different PC. There's a lot of reference to "localhost" in the client folder code, so it you are trying to run on another PC/server, container or vm this isn''t going to work. I had to update the localhost references in code to privateGPT host machine IP to get this to work. This may be something that can be addressed in future not hard coding "localhost".
> 
> Will you be able to share or let me know which refence files you have changed?

I was able to find the files changed it to the IP and its working now thank you @bradsec all of you that tried to help
