### ISSUE TITLE
server run error

### ISSUE THREAD

**Issue by rexzhang2023** [SamurAIGPT/privateGPT#3]
(pgweb) rex@alienware17B:~/pgweb/privateGPT/server$ python privateGPT.py
/home/rex/pgweb/privateGPT/server/privateGPT.py:1: DeprecationWarning: 'flask.Markup' is deprecated and will be removed in Flask 2.4. Import 'markupsafe.Markup' instead.
  from flask import Flask,jsonify, render_template, flash, redirect, url_for, Markup, request
Traceback (most recent call last):
  File "/home/rex/pgweb/privateGPT/server/privateGPT.py", line 213, in <module>
    load_model()
  File "/home/rex/pgweb/privateGPT/server/privateGPT.py", line 210, in load_model
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/home/rex/miniconda3/envs/pgweb/lib/python3.11/site-packages/langchain/llms/gpt4all.py", line 170, in validate_environment
    model_path=values["model"],
               ~~~~~~^^^^^^^^^
KeyError: 'model'

**Comment by rexzhang2023** [comment]
after update I got 404
gweb) rex@alienware17B:~/pgweb/privateGPT/server$ python privateGPT.py
/home/rex/pgweb/privateGPT/server/privateGPT.py:1: DeprecationWarning: 'flask.Markup' is deprecated and will be removed in Flask 2.4. Import 'markupsafe.Markup' instead.
  from flask import Flask,jsonify, render_template, flash, redirect, url_for, Markup, request
LLM0 None
 * Serving Flask app 'privateGPT'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.147.215:5000
Press CTRL+C to quit
 * Restarting with stat
/home/rex/pgweb/privateGPT/server/privateGPT.py:1: DeprecationWarning: 'flask.Markup' is deprecated and will be removed in Flask 2.4. Import 'markupsafe.Markup' instead.
  from flask import Flask,jsonify, render_template, flash, redirect, url_for, Markup, request
LLM0 None
 * Debugger is active!
 * Debugger PIN: 360-057-537
127.0.0.1 - - [26/May/2023 16:43:14] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [26/May/2023 16:43:14] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/May/2023 16:43:20] "GET / HTTP/1.1" 404 -

**Comment by Anil-matcha** [comment]
Looks like the server is running, there is no error
Once you are able to successfully run the client, go to localhost:3000 and start using the app

**Comment by dKonsalik** [comment]
Hello, I am also getting 404 not found when when going to http://192.168.20.50:5000/
* Serving Flask app 'privateGPT'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.20.50:5000
Press CTRL+C to quit
192.168.70.36 - - [29/May/2023 15:48:07] "GET / HTTP/1.1" 404 -


http://192.168.20.50:3000 works but can't upload a document gives error

**Comment by Anil-matcha** [comment]
@dKonsalik What error are you facing with uploading

**Comment by dKonsalik** [comment]
Error uploading document, I am trying to upload a PDF
