### ISSUE TITLE
Error when upload the file and ingest data

### ISSUE THREAD

**Issue by gabrielvalladao** [SamurAIGPT/privateGPT#30]
Unhandled Runtime Error
ReferenceError: response is not defined

Source
components\ConfigSideNav.js (27:3) @ response

  25 |   } catch (error) {
  26 |     setIsLoading(false);
> 27 | 	response.text().then(text => {toast.error("Error Ingesting data."+text);})
     | 	 ^
  28 |   }
  29 | };
  30 |

**Comment by Anil-matcha** [comment]
Please check if huggingface sentence transformers are being downloaded during ingest

**Comment by gabrielvalladao** [comment]
Solved, need install some pip packages, and upgrade python, tnkxs!
