### ISSUE TITLE
Could not find a version that satisfies the requirement gpt4all==0.2.3

### ISSUE THREAD

**Issue by thanhtantran** [SamurAIGPT/privateGPT#33]
Hello,

I run the command `pip3 install -r requirements.txt` and get this error

`ERROR: Could not find a version that satisfies the requirement gpt4all==0.2.3 (from versions: 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for gpt4all==0.2.3
`

**Comment by thanhtantran** [comment]
My pip is `pip-23.1.2-py3` but still get same error

However your docker run smoothly

**Comment by thanhtantran** [comment]
Ah, i figure out the problem. 
I try to run privateGPT on Orange Pi 5, an arm64 machine. When installing gpt4all using pip the highest version supported is 0.1.7.

If i modify the requirements.txt to 0.17, does it work?

**Comment by RattyDAVE** [comment]
Thank you. I have just done it for myself like all my projects. If it is of use to someone else that I am all for that.

**Comment by RattyDAVE** [comment]
Orange Pi 5! That's optimistic! 

I like your thinking.

Have you tried removing the pip/pip3 you have installed and getting the version using the following command:

```
curl https://bootstrap.pypa.io/get-pip.py | python3
```

**Comment by Anil-matcha** [comment]
You need 16GB RAM to be able to run the model. So Orange Pi 5 might not be an ideal one to run it

**Comment by thanhtantran** [comment]
> You need 16GB RAM to be able to run the model. So Orange Pi 5 might not be an ideal one to run it

I am using Orange Pi 5 with 16GB RAM, the only problem is gpt4all not match required version

BTW, Dockerised version of @RattyDAVE doesn't work on ARM64 machine

**Comment by RattyDAVE** [comment]
> BTW, Dockerised version of @RattyDAVE doesn't work on ARM64 machine

Uploading now.

**Comment by RattyDAVE** [comment]
> BTW, Dockerised version of @RattyDAVE doesn't work on ARM64 machine

ARM64 does not have Python Module gpt4all==0.2.3 

So that's bad news.

**Comment by Anil-matcha** [comment]
Closing as not related
