### ISSUE TITLE
error running python privateGPT. help

### ISSUE THREAD

**Issue by xhorizont** [SamurAIGPT/privateGPT#47]
Running in /server 

python privateGPT.  error

Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

or python3 privateGPT. error

python3: can't open file '/home/ai1/privateGPT/server/privateGPT.': [Errno 2] No such file or directory

**Comment by Anil-matcha** [comment]
Please install Python in your system

**Comment by xhorizont** [comment]
Somehow needed to install python-is-python3
