### ISSUE TITLE
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ZimaBlueee** [SamurAIGPT/privateGPT#50]
operating system：CentOS Linux release 7.9.2009 (Core)
python：3.8.16（conda）

when i execute `pip install -r requirements.txt`
![image](https://github.com/SamurAIGPT/privateGPT/assets/53747502/357eccc9-dd82-4d61-b909-41ba50f51fb9)

**Comment by ZimaBlueee** [comment]
upgrade to g++11

**Comment by aistart** [comment]
Download visual code VisualStudioSetup.ext, then install C++ desktop dev. 
After that, redo: pip install -r requirements.txt
