### ISSUE TITLE
No such file or directory 'models/ggml-gpt4all-j-v1.3-groovy.bin

### ISSUE THREAD

**Issue by clearsitedesigns** [SamurAIGPT/privateGPT#9]
I got this all setup with a few issues. Nothing ran into an issue when starting setup on the local environments. I took a simple text document, uploaded, ingest data - then when I go to Download model,

This is the error that is showing up... 

No such file or directory 'models/ggml-gpt4all-j-v1.3-groovy.bin

**Comment by nahart86** [comment]
I ran into the same problem, I had to manually download it from here and create a new "models" directory inside the "server" directory and drop the bin file there - You can find the module here, but you can also look in the privateGPT.py code and fine it too: 'https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin'

**Comment by Anil-matcha** [comment]
You need to click on "Download" button in UI first before you go and run your queries

**Comment by Francosurf** [comment]
same problem, i clicked but i received an error.

**Comment by Jiashisoft** [comment]
me too,i am also  No such file or directory: 'models/ggml-gpt4all-j-v1.3-groovy.bin'
127.0.0.1 - - "GET /download_model HTTP/1.1" 500 -

**Comment by dzungpv** [comment]
> I ran into the same problem, I had to manually download it from here and create a new "models" directory inside the "server" directory and drop the bin file there - You can find the module here, but you can also look in the privateGPT.py code and fine it too: 'https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin'

It not working, after I follow your guide it show error: "Error getting data.Model not downloaded" when enter chat content.

**Comment by Anil-matcha** [comment]
This issue has been fixed now, please check
